# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_remove_user_student_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_of', to='math_app.User'),
            preserve_default=False,
        ),
    ]
